"""
Report Generation Module
Creates HTML, JSON, CSV, and console reports
"""

import json
import csv
from datetime import datetime
from pathlib import Path
from colorama import Fore, Style
from tabulate import tabulate

class ReportGenerator:
    def __init__(self, output_dir):
        self.output_dir = output_dir
        self.timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
    def generate_html(self, report_data):
        """Generate HTML report"""
        html_file = self.output_dir / f"report_{self.timestamp}.html"
        
        # Count by severity
        severity_counts = {'CRITICAL': 0, 'HIGH': 0, 'MEDIUM': 0, 'LOW': 0}
        for finding in report_data['findings']:
            severity = finding.get('severity', 'LOW')
            severity_counts[severity] = severity_counts.get(severity, 0) + 1
        
        html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <title>PreFlight Security Report - {report_data['target']}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }}
        .container {{ max-width: 1200px; margin: auto; background: white; padding: 20px; border-radius: 10px; }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px; margin-bottom: 20px; }}
        .severity-critical {{ color: #dc3545; font-weight: bold; }}
        .severity-high {{ color: #fd7e14; font-weight: bold; }}
        .severity-medium {{ color: #ffc107; font-weight: bold; }}
        .severity-low {{ color: #28a745; font-weight: bold; }}
        .finding {{ border-left: 4px solid; margin: 10px 0; padding: 10px; background: #f8f9fa; }}
        .cvss {{ font-family: monospace; background: #e9ecef; padding: 5px; border-radius: 3px; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background-color: #667eea; color: white; }}
        .summary-stats {{ display: flex; gap: 20px; margin: 20px 0; }}
        .stat-card {{ flex: 1; background: #f8f9fa; padding: 15px; border-radius: 5px; text-align: center; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔒 PreFlight Security Scanner Report</h1>
            <p><strong>Target:</strong> {report_data['target']}</p>
            <p><strong>Scan Time:</strong> {report_data['scan_time']}</p>
            <p><strong>Duration:</strong> {report_data['duration_seconds']:.2f} seconds</p>
            <p><strong>Authenticated Scan:</strong> {report_data['authenticated']}</p>
        </div>
        
        <div class="summary-stats">
            <div class="stat-card">
                <h3>Total Findings</h3>
                <h2>{report_data['total_findings']}</h2>
            </div>
            <div class="stat-card">
                <h3>Critical</h3>
                <h2 class="severity-critical">{severity_counts['CRITICAL']}</h2>
            </div>
            <div class="stat-card">
                <h3>High</h3>
                <h2 class="severity-high">{severity_counts['HIGH']}</h2>
            </div>
            <div class="stat-card">
                <h3>Medium</h3>
                <h2 class="severity-medium">{severity_counts['MEDIUM']}</h2>
            </div>
            <div class="stat-card">
                <h3>Low</h3>
                <h2 class="severity-low">{severity_counts['LOW']}</h2>
            </div>
        </div>
        
        <h2>📋 Vulnerability Details</h2>
        <table>
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Severity</th>
                    <th>CVSS Score</th>
                    <th>OWASP</th>
                    <th>Remediation</th>
                </tr>
            </thead>
            <tbody>
        """
        
        for finding in report_data['findings']:
            cvss_data = finding.get('cvss', {})
            cvss_score = cvss_data.get('score', 'N/A')
            severity_class = f"severity-{finding.get('severity', 'low').lower()}"
            
            html_content += f"""
                <tr>
                    <td>{finding.get('title', 'N/A')}</td>
                    <td class="{severity_class}">{finding.get('severity', 'N/A')}</td>
                    <td>{cvss_score}</td>
                    <td>{finding.get('owasp', finding.get('api_owasp', 'N/A'))}</td>
                    <td>{finding.get('remediation', 'N/A')}</td>
                </tr>
            """
        
        html_content += """
            </tbody>
        </table>
        
        <div class="footer" style="margin-top: 40px; padding: 20px; background: #e9ecef; border-radius: 5px;">
            <p><strong>⚠️ Disclaimer:</strong> This report is generated by an automated tool for educational purposes.</p>
            <p>Always verify findings manually before taking remediation actions.</p>
            <p><em>Generated by PreFlight Security Scanner v1.0</em></p>
        </div>
    </div>
</body>
</html>
        """
        
        with open(html_file, 'w') as f:
            f.write(html_content)
        
        print(f"{Fore.GREEN}[✓] HTML report saved: {html_file}{Style.RESET_ALL}")
        return html_file
    
    def generate_json(self, report_data):
        """Generate JSON report"""
        json_file = self.output_dir / f"report_{self.timestamp}.json"
        
        with open(json_file, 'w') as f:
            json.dump(report_data, f, indent=2)
        
        print(f"{Fore.GREEN}[✓] JSON report saved: {json_file}{Style.RESET_ALL}")
        return json_file
    
    def generate_csv(self, findings):
        """Generate CSV report"""
        csv_file = self.output_dir / f"findings_{self.timestamp}.csv"
        
        if findings:
            with open(csv_file, 'w', newline='') as f:
                writer = csv.DictWriter(f, fieldnames=['title', 'severity', 'cvss_score', 'owasp', 'cwe', 'remediation', 'evidence'])
                writer.writeheader()
                
                for finding in findings:
                    cvss_data = finding.get('cvss', {})
                    writer.writerow({
                        'title': finding.get('title', ''),
                        'severity': finding.get('severity', ''),
                        'cvss_score': cvss_data.get('score', ''),
                        'owasp': finding.get('owasp', finding.get('api_owasp', '')),
                        'cwe': finding.get('cwe', ''),
                        'remediation': finding.get('remediation', ''),
                        'evidence': finding.get('evidence', '')
                    })
        
        print(f"{Fore.GREEN}[✓] CSV report saved: {csv_file}{Style.RESET_ALL}")
        return csv_file
    
    def generate_console_summary(self, report_data):
        """Generate console summary with color"""
        print(f"\n{Fore.CYAN}{'='*60}")
        print(f"{Fore.YELLOW}📊 SCAN SUMMARY")
        print(f"{Fore.CYAN}{'='*60}{Style.RESET_ALL}")
        
        # Prepare findings table
        table_data = []
        for finding in report_data['findings'][:20]:  # Show first 20
            cvss_score = finding.get('cvss', {}).get('score', 'N/A')
            severity = finding.get('severity', 'UNKNOWN')
            
            # Color severity
            if severity == 'CRITICAL':
                severity_colored = f"{Fore.RED}{severity}{Style.RESET_ALL}"
            elif severity == 'HIGH':
                severity_colored = f"{Fore.YELLOW}{severity}{Style.RESET_ALL}"
            elif severity == 'MEDIUM':
                severity_colored = f"{Fore.BLUE}{severity}{Style.RESET_ALL}"
            else:
                severity_colored = f"{Fore.GREEN}{severity}{Style.RESET_ALL}"
            
            table_data.append([
                finding.get('title', 'N/A')[:50],
                severity_colored,
                cvss_score,
                finding.get('owasp', finding.get('api_owasp', 'N/A'))
            ])
        
        if table_data:
            print(tabulate(table_data, headers=['Finding', 'Severity', 'CVSS', 'OWASP'], tablefmt='grid'))
        
        # Critical findings warning
        critical_count = sum(1 for f in report_data['findings'] if f.get('severity') == 'CRITICAL')
        if critical_count > 0:
            print(f"\n{Fore.RED}{'⚠️ ' * 10}")
            print(f"{Fore.RED}CRITICAL: {critical_count} CRITICAL findings detected!")
            print(f"{Fore.RED}DO NOT DEPLOY TO PRODUCTION!")
            print(f"{Fore.RED}{'⚠️ ' * 10}{Style.RESET_ALL}")